CREATE TABLE `users_new` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` tinytext NOT NULL,
  `last_name` tinytext NOT NULL,
  `name` tinytext NOT NULL,
  `age` tinyint(4) DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `gender` tinyint(1) DEFAULT NULL,
  `political` varchar(45) DEFAULT NULL,
  `middle_name` tinytext,
  `location` varchar(45) DEFAULT NULL,
  `religion` varchar(45) DEFAULT NULL,
  `zip` tinyint(4) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `education` varchar(45) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `updated_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL,
  `access_token` varchar(100) DEFAULT NULL,
  `refresh_token` varchar(100) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `facebook_id` bigint(25) DEFAULT NULL,
  `facebook_session_token` varchar(200) DEFAULT NULL,
  `t_level` tinyint(1) NOT NULL DEFAULT '1',
  `linkedin_id` varchar(20) DEFAULT NULL,
  `linkedin_session_token` varchar(100) DEFAULT NULL,
  `linkedin_profile_image` varchar(200) DEFAULT NULL,
  `bio` varchar(200) DEFAULT NULL,
  `follower_count` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1016 DEFAULT CHARSET=utf8;
